# fly.toml app configuration file generated for fleetops-telemetry-publisher on 2026-08-12T09:00:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fleetops-telemetry-publisher'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
